version: "3"
services:
  server:
    build: .
    ports:
      - "8080:8080"
#    environment:
#      - spring.datasource.url=jdbc:jdbc:mysql://mysql:3306/customer?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    networks:
      - springmysql-net
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=customer
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

networks:
  springmysql-net: